language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com

otp_release:
        - 20.0
        - 19.3
        - 18.3

sudo: required
services:
        - docker

before_script:
        - make mongooseim-start
        - make

script:
        - make test
        - make ct
        - make dialyzer

after_script:
        - make mongooseim-stop
